
# This triggers builds to run on the new TravisCI infrastructure.
# See: http://docs.travis-ci.com/user/workers/container-based-infrastructure/
sudo: true

## requires mac os pbcopy and pbpaste commands.
os: osx
osx_image: xcode9.3beta

before_install:
- sudo mkdir /usr/local/sbin
- sudo chown -R travis /usr/local/sbin
- brew update
- brew outdated
- brew upgrade
- brew install git-lfs
- brew install homebrew/php/php71
- brew install composer


env:
  - COMPOSER_OPTS=""
  - COMPOSER_OPTS="--prefer-lowest"

install:
    - travis_retry composer update --prefer-dist $COMPOSER_OPTS

before_script:
  - git lfs pull
  - travis_retry composer update ${COMPOSER_FLAGS} --no-interaction --prefer-dist

script:
  - vendor/bin/phpcs --standard=psr2 src/
  - vendor/bin/phpunit --coverage-text --coverage-clover=coverage.clover

after_script:
  - |
    if [[ "$TRAVIS_PHP_VERSION" != 'hhvm' && "$TRAVIS_PHP_VERSION" != '7.0' ]]; then
      wget https://scrutinizer-ci.com/ocular.phar
      php ocular.phar code-coverage:upload --format=php-clover coverage.clover
    fi
